[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
xargo = false
pre-build = ["apt-get -q update && apt-get -yq install libssl-dev && apt-get clean && rm -rf /var/lib/apt/lists/*"]

# [target.x86_64-unknown-linux-gnu.image]
# name = "tradebot-build"
# toolchain = ["x86_64-unknown-linux-gnu"]

[target.x86_64-unknown-linux-gnu.dockerfile]
file = "./Dockerfile"
context = "."
build-args = { ARCH = "amd64" }
